services:
  wordpress:
    build:
      context: .
      dockerfile: wordpress.dockerfile
    environment:
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: wordpress
    volumes:
      - src:/var/www/html
      - ./config/php-fpm.conf:/etc/php81/php-fpm.conf
      - ./config/php.ini:/etc/php81/php.ini
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    volumes:
      - src:/var/www/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 443:443
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
  src:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/src
      o: bind